require_relative 'configurators/base'
require_relative 'configurators/active_admin'
require_relative 'configurators/form_framework'
require_relative 'configurators/image_magick'
require_relative 'configurators/monitoring'
require_relative 'configurators/sentry'
require_relative 'configurators/postgres_database_uuids'
require_relative 'configurators/ci'
